config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands
  resources :albums
  resources :tracks
  resources :notes, only: [:new, :create]

  root 'bands#index'
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :band
  has_many :tracks, dependent: :destroy


end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :albums, dependent: :destroy

end

app/models/note.rb
class Note < ActiveRecord::Base

  belongs_to :user
  belongs_to :track
  
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
  has_many :notes

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :notes

  # BASIC AUTHENTICATION
  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  # is this really necessary since ensure_session_tokens uses ||=?
  def self.generate_session_token
    session_token = SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    save!
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    Album.all
    render :index
  end

  def new
    @band = Band.find(params[:band_id])
    @album = @band.albums.new

    render :new
  end

  def create


    @album = Album.new(album_params)

    if @album.save
      redirect_to band_url(album_params[:band_id])
    else
      render :new
    end
  end

  def edit
    @album = Album.new(album_params)
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    # redundant with edit?
  end

  def destroy
    @album = album.find(params[:id])
    @album.delete
  end

  private
  def album_params
    params.require(:album).permit(:title, :yr, :band_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?, :ensure_signed_in, :ensure_signed_out

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def sign_in!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def sign_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def signed_in?
    !!current_user
  end

  def ensure_signed_in
    unless signed_in?
      flash[:errors] = ["Must be signed in."]
      redirect_to new_user_url
    end
  end

  def ensure_signed_out
    if signed_in?
      flash[:errors] = ["Already logged in."]
      redirect_to new_user_url
    end
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      render :new
    end
  end

  def edit
    @band = Band.new(band_params)
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    # redundant with edit?
  end

  def destroy
    @band = Band.find(params[:id])
    @band.delete
  end

  private
  def band_params
    params.require(:band).permit(:name, :albums)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def new
    @track = Track.find(params[:id])
    @note = @track.notes.new

    render track_url(note_params[:track_id])
  end

  def create
    @note = Note.new(note_params)
    if @note.user_id.nil?
      @note.user_id = current_user.id
    end
    if @note.track_id.nil?
      @note.track_id = params[:id]
    end

    if @note.save
      redirect_to track_url(note_params[:track_id])
    else
      # or just render the track page
      render track_url(note_params[:track_id])
    end
  end
  #
  # def edit
  #   @track = Track.new(track_params)
  #   render :edit
  # end

  private
  def note_params
    params.require(:note).permit(:title, :body, :user_id, :track_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
      )

    if @user
      sign_in!(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def destroy
    sign_out!
    redirect_to new_user_url
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @album = Album.find(params[:album_id])
    @track = @album.tracks.new

    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to album_url(track_params[:album_id])
    else
      render :new
    end
  end

  def edit
    @track = Track.new(track_params)
    render :edit
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def update
    # redundant with edit?
  end

  def destroy
    @track = Track.find(params[:id])
    @track.delete
  end

  private
  def track_params
    params.require(:track).permit(:name, :album_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_signed_in, only: [:show]
  
  def new
    render :new
  end

  def show
    render :show
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    <<-HTML.html_safe
      <input
      type="hidden"
      name="authenticity_token"
      value="#{h(form_authenticity_token)}">
    HTML
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<h1>All Albums</h1>

<table>
  <tr>
    <td>Album</td>
    <td>Band</td>
    <td>Edit</td>
  </tr>
  <% @albums.each do |album| %>
  <tr>
    <td><%= album.title %></td>
    <td><%= Band.find(album.band_id).name %></td>
    <td><a href="<%= albums_url %>">Edit</a></td>
  </tr>
  <% end %>
</table>

<a href="<%= new_album_url %>">Add Album</a>

app/views/albums/new.html.erb
<h1>New Album</h1>

<form action="<%= albums_url %>" method="post">
    <%= auth_token %>
    <br>
    <label>Title
      <input type="text" name="album[title]" value="<%= @album.title %>">
    </label>
    <br>
    <label>Year
      <input type="text" name="album[yr]" value="<%= @album.yr %>">
    </label>
    <br>
    <input type="hidden" name="album[band_id]" value="<%= @band.id %>">
    <br>
    <button>Submit</button>
</form>

<a href="<%= bands_url %>">All Bands</a>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<br>
<a href="<%= band_url(@album.band_id) %>">Band</a>
<br>
<br>
<table>
  <% @album.tracks.each do |track| %>
  <tr>
    <td><%= track.name %></td>
    <td> <a href="<%= track_url(track.id) %>">View Track</a> </td>
  </tr>
  <% end %>
</table>

<br>
<form action="<%= new_track_url %>" method="get">
  <input type="hidden" name="album_id" value="<%= @album.id %>">
  <button>Add Track</button>
</form>
<a href="<%= bands_url %>">All Bands</a>

app/views/bands/index.html.erb
<h1>Bands Index</h1>

<table>
  <tr>
    <td>
      Name
    </td>
    <td>
      Edit
    </td>
  </tr>
  <% @bands.each do |band| %>
  <tr>
    <td>
      <%= band.name %>
    </td>
    <td>
      <a href="<%= band_url(band.id) %>">View</a>
    </td>
    <td>
      <a href="<%= bands_url %>">Edit</a>
    </td>
  </tr>
  <% end %>
</table>

<a href="<%= new_band_url %>">Add Band</a>

app/views/bands/new.html.erb
<h1>New Band</h1>

<form action="<%= bands_url %>" method="post">
    <%= auth_token %>

    <label>Band Name
      <input type="text" name="band[name]" value="<%= @band.name %>">
    </label>

    <button>Submit</button>
</form>

<a href="<%= bands_url %>">All Bands</a>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<br>
<a href="<%= tracks_url %>">All Tracks</a>
<br>
<br>
<table>
  <% @band.albums.each do |album| %>
  <tr>
    <td><%= album.title %></td>
    <td><%= album.yr %></td>
    <td><%= album.tracks.count %></td>
    <td>
      <a href="<%= album_url(album.id) %>">Tracks</a>
    </td>
  </tr>
  <% end %>
</table>

<br>
<form action="<%= new_album_url %>" method="get">
  <input type="hidden" name="band_id" value="<%= @band.id %>">
  <button>Add Album</button>
</form>
<a href="<%= bands_url %>">All Bands</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if signed_in? %>
  <label>Logged in as <%= current_user.email %></label>
    <form action="<%= session_url  %>" method="post">
      <%= auth_token %>
      <input type="hidden" name="_method" value="delete">
      <button>Log Out</button>
    </form>
  <% else %>
    <a href="<%= new_session_url  %>">Log In</a>
  <% end %>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<form action="<%= notes_url %>" method="post">
  <%= auth_token %>

  <label>Title
    <input type="string" name="note[title]" value="">
  </label>
  <br>
  <textarea name="note[body]" rows="8" cols="40"></textarea>
  <br>
  <input type="hidden" name="note[track_id]" value="<%= track.id %>">
  <button>Submit</button>
</form>

app/views/notes/_note.html.erb
<h2> <%= note.title =%> </h2>
<h3> by <%= User.find(note.user_id).email %> </h3>
<p>
  <%= note.body %>
</p>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<form action="<%= tracks_url %>" method="post">
    <%= auth_token %>
    <br>
    <label>Name
      <input type="text" name="track[name]" value="<%= @track.name %>">
    </label>
    <br>

    <input type="hidden" name="track[album_id]" value="<%= @track.album_id %>">
    <br>
    <button>Submit</button>
</form>

<a href="<%= album_url(@track.album_id) %>">Back to Album</a>
<br>
<a href="<%= bands_url %>">All Bands</a>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>
<br>
<a href="<%= album_url(@track.album_id) %>">Album</a>
<br>
<br>
<table>
</table>

<a href="<%= bands_url %>">All Bands</a>
<br>

<%= render partial: 'notes/form', locals: {track: @track} %>
<% @track.notes.each do |note| %>
  <%= render partial: 'notes/note', locals: {track: @track, note: note} %>
<% end %>

app/views/users/login.html.erb
<h1>Sign In</h1>

<form action="<%= bands_url %>" method="post">
  <%= auth_token %>
  <label>email <br>
    <input type="text" name="user[email]" value="">
  </label>
  <br>
  <label>password <br>
    <input type="password" name="user[password]" value="">
  </label>
  <br>
  <button>Sign In</button>
</form>

app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%= user_url %>" method="post">
  <% auth_token %>
  <label>email <br>
    <input type="text" name="user[email]" value="">
  </label>
  <br>
  <label>password <br>
    <input type="password" name="user[password]" value="">
  </label>
  <br>
  <button>Sign Up</button>
</form>

app/views/users/show.html.erb
<h1>Hello <%= current_user.email %> </h1>
<a href="<%= bands_url %>">All Bands</a>